package com.vuravision.classroom
import android.graphics.*
import android.view.*
import android.widget.*
import android.os.Looper
import java.io.File
import kotlin.math.*
import org.junit.*
import org.junit.Assert.*
import org.junit.runner.RunWith
import org.robolectric.*
import org.robolectric.annotation.*
import org.robolectric.shadows.ShadowDialog
@RunWith(RobolectricTestRunner::class)
@Config(sdk=[28],qualifiers="en-land-xhdpi")
@GraphicsMode(GraphicsMode.Mode.NATIVE)
class Version11Test {
 private val ctx get()=RuntimeEnvironment.getApplication()
 private lateinit var media:Media
 private lateinit var board:Board
 private lateinit var store:Store
 @Before fun setup(){ctx.getSharedPreferences("vura",0).edit().clear().commit();media=Media(ctx);store=Store();board=Board(ctx,store,Renderer(media));board.layout(0,0,1600,1000)}
 @After fun close(){media.close()}
 private fun touch(action:Int,x:Float,y:Float){val d=ctx.resources.displayMetrics.density;val e=MotionEvent.obtain(100,200,action,x*d,y*d,0);board.onTouchEvent(e);e.recycle()}
 private fun drag(x:Float,y:Float,xx:Float,yy:Float){touch(0,x,y);touch(2,xx,yy);touch(1,xx,yy)}
 @Test fun dualTipsChooseIndependentAppearanceIncludingReportedStylus(){val p=TouchProfile(calibrated=true,thin=10f,palm=60f,thickWidth=13f,thickColor=Color.RED);for(tool in listOf(1,2)){assertEquals(3f,p.width(tool,5f,3f));assertEquals(13f,p.width(tool,25f,3f));assertEquals(Color.BLUE,p.color(tool,5f,Color.BLUE));assertEquals(Color.RED,p.color(tool,25f,Color.BLUE))};assertEquals(Color.BLUE,p.color(2,0f,Color.BLUE))}
 @Test fun areaEraserPreservesObjectAndHistory(){val o=Item(kind="shape",shape="rectangle",x=20f,y=20f,w=160f,h=100f);store.page.items.add(o);board.tool="erase";board.eraserMode="area";drag(95f,0f,95f,150f);assertEquals(1,store.page.items.size);assertTrue(o.cuts.isNotEmpty());assertFalse(o.hit(95f,20f,0f));assertTrue(o.hit(40f,20f,0f));store.undo();assertTrue(store.page.items.single().cuts.isEmpty());store.redo();assertTrue(store.page.items.single().cuts.isNotEmpty())}
 @Test fun fastWholeEraserCannotJumpOverInk(){store.page.items.add(Item(x=100f,y=30f,w=1f,h=80f,inkW=1f,inkH=80f,points=mutableListOf(Point(0f,0f),Point(0f,80f))));board.tool="erase";drag(0f,60f,200f,60f);assertTrue(store.page.items.isEmpty())}
 @Test fun masksActuallyRemovePixelsAndFollowResize(){val o=Item(kind="sticky",text="",w=200f,h=100f,noteColor=Color.RED);Erasing.cut(o,PointF(80f,0f),PointF(80f,100f),10f);val b=Bitmap.createBitmap(500,220,Bitmap.Config.ARGB_8888);val c=Canvas(b);Renderer(media).draw(c,o);assertEquals(0,Color.alpha(b.getPixel(80,50)));assertEquals(Color.RED,b.getPixel(30,50));o.w=400f;o.h=200f;b.eraseColor(0);Renderer(media).draw(c,o);assertEquals(0,Color.alpha(b.getPixel(160,100)));assertEquals(Color.RED,b.getPixel(60,100));b.recycle()}
 @Test fun pdfErasuresAreScopedToCurrentPage(){val o=Item(kind="pdf",pageCount=3,pdfPage=1);Erasing.cut(o,PointF(50f,30f),PointF(70f,30f),10f);assertFalse(o.hit(60f,30f,0f));o.pdfPage=0;assertTrue(o.hit(60f,30f,0f));o.locked=true;assertFalse(Erasing.cut(o,PointF(),PointF(),10f))}
 @Test fun textBoundsAndStylesMatchRenderedLayout(){val o=Item(kind="text",text="Hi",width=24f,bold=true,textAlign="center",color=Color.BLUE);TextLayout.fit(o);assertTrue(o.w<80f);assertTrue(o.h<70f);assertTrue(TextLayout.paint(o).typeface.isBold);assertEquals(Color.BLUE,TextLayout.paint(o).color);o.text="First line\nSecond line";TextLayout.fit(o);assertEquals(TextLayout.layout(o).height+18f,o.h);assertEquals(android.text.Layout.Alignment.ALIGN_CENTER,TextLayout.layout(o).alignment)}
 @Test fun linesKeepStartAndEndInAllQuadrants(){board.tool="shape";board.shape="arrow";for(dx in listOf(-90f,90f))for(dy in listOf(-60f,60f)){drag(200f,200f,200f+dx,200f+dy);val o=store.page.items.last();assertEquals(dx<0,o.flipX);assertEquals(dy>=0,o.flipY);assertEquals(90f,o.w);assertEquals(60f,o.h)}}
 @Test fun uniformShapesAndCylinderCaps(){board.tool="shape";board.shape="circle";drag(200f,200f,100f,160f);val o=store.page.items.single();assertEquals(o.w,o.h);assertEquals(100f,o.x);assertEquals(100f,o.y);assertEquals(Shapes.capDepth(100f,100f),Shapes.capDepth(100f,400f));assertFalse(Shapes.uniform("cylinder"));assertTrue(Shapes.uniform("square"))}
 @Test fun pdfVerticalDragMovesWithoutChangingPage(){val o=Item(kind="pdf",x=100f,y=100f,w=200f,h=300f,pageCount=3);store.page.items.add(o);board.tool="select";drag(180f,280f,185f,160f);assertEquals(0,o.pdfPage);assertEquals(-20f,o.y);assertEquals(105f,o.x)}
 @Test fun selectionSecondTapOpensActionsButDragDoesNot(){val host=Robolectric.buildActivity(android.app.Activity::class.java).setup();host.get().setContentView(board);val o=Item(kind="shape",x=100f,y=100f,w=200f,h=150f);store.page.items.add(o);board.tool="select";var calls=0;board.onObjectActions={calls++};drag(170f,170f,170f,170f);Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals(0,calls);drag(170f,170f,170f,170f);Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals(1,calls);drag(170f,170f,190f,170f);Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals(1,calls);host.pause().stop().destroy()}
 @Test fun automaticSmartShapeNeedsNoRepeatedButton(){board.tool="smart";board.smartMode="shape";repeat(2){drag(50f,50f+it*60,220f,50f+it*60)};assertEquals(2,store.page.items.size);assertTrue(store.page.items.all{it.kind=="shape"&&it.shape=="line"})}
 @Test fun lassoUsesPolygonAndIgnoresLockedItems(){val pts=(0..40).map{val a=it*PI/20;Point((100+90*cos(a)).toFloat(),(100+90*sin(a)).toFloat())}.toMutableList();val loop=Item(w=200f,h=200f,inkW=200f,inkH=200f,points=pts);val inside=Item(kind="text",x=80f,y=80f,w=20f,h=20f);val outside=inside.copy(id=newId(),x=300f);val locked=inside.copy(id=newId(),locked=true);assertTrue(SmartSelection.isLoop(loop));assertEquals(listOf(inside),SmartSelection.enclosed(loop,listOf(inside,outside,locked)))}
 @Test fun mathSupportsPersianNumbersLinearQuadraticAndFunctions(){assertEquals("14",SmartMath.result("۲*(۳+۴)"));assertEquals("x = 4",SmartMath.result("2x+3=11"));assertEquals("x = -3 or x = 3",SmartMath.result("x^2=9"));assertEquals("No real roots",SmartMath.solve("x^2+1=0"));assertEquals("1",SmartMath.result("exp(0)"));assertEquals(3.0,MathTools().compile("y=2x-5")(4.0),1e-9);assertEquals(1.0,MathTools().compile("sin(x)")(PI/2),1e-9)}
 @Test fun invalidEquationsNeverReturnGuessedAnswers(){listOf("x^3=8","1/x=2","x+1","2*(3+").forEach{assertThrows(Exception::class.java){SmartMath.result(it)}};assertEquals("All real x",SmartMath.solve("2x=2x"));assertEquals("No solution",SmartMath.solve("2x=2x+1"));assertNotEquals(Long.MAX_VALUE.toString(),MathTools.format(1e30))}
 @Test fun penEraserSmartAndTextDialogsRender(){val ctl=Robolectric.buildActivity(MainActivity::class.java).setup();val a=ctl.get();try{for((method,name)in listOf("penSettings" to "pen-v11","eraserSettings" to "eraser-v11","smart" to "smart-v11")){MainActivity::class.java.getDeclaredMethod(method).apply{isAccessible=true}.invoke(a);val d=ShadowDialog.getLatestDialog();capture(d.window!!.decorView,name);d.dismiss()};MainActivity::class.java.getDeclaredMethod("addText",Boolean::class.javaPrimitiveType).apply{isAccessible=true}.invoke(a,false);val d=ShadowDialog.getLatestDialog();assertTrue(views(d.window!!.decorView).filterIsInstance<CheckBox>().any());capture(d.window!!.decorView,"text-v11");d.dismiss()}finally{ctl.pause().stop().destroy()}}
 @Test fun hiddenSettingsOpenOnExactlyThreeGuideTaps(){val ctl=Robolectric.buildActivity(MainActivity::class.java).setup();val a=ctl.get();try{MainActivity::class.java.getDeclaredMethod("quickGuide").apply{isAccessible=true}.invoke(a);val d=ShadowDialog.getLatestDialog();val title=views(d.window!!.decorView).filterIsInstance<TextView>().first{it.text=="Learn VuraVision"};repeat(2){title.performClick()};assertFalse(ctx.getSharedPreferences("vura",0).getBoolean("engineering",false));title.performClick();assertTrue(ctx.getSharedPreferences("vura",0).getBoolean("engineering",false));ShadowDialog.getLatestDialog().dismiss()}finally{ctl.pause().stop().destroy()}}
 @Test fun newStylesAndMasksSurviveSaveAndOldDocumentsHaveDefaults(){val g=com.google.gson.Gson();val old=g.fromJson("{\"kind\":\"text\",\"text\":\"Old lesson\"}",Item::class.java);assertTrue(old.cuts.isEmpty());assertEquals("start",old.textAlign);val o=Item(kind="sticky",bold=true,textAlign="end",noteColor=Color.GREEN,flipX=true);Erasing.cut(o,PointF(20f,20f),PointF(40f,40f),8f);val copy=g.fromJson(g.toJson(o),Item::class.java);assertEquals(o,copy);Lesson(pages=mutableListOf(Page(items=mutableListOf(copy)))).validate()}
 private fun views(v:View):List<View> = listOf(v)+if(v is ViewGroup)(0 until v.childCount).flatMap{views(v.getChildAt(it))}else emptyList()
 private fun capture(v:View,name:String){views(v).forEach{it.setScrollIndicators(0)};val w=1200;val h=1500;v.measure(View.MeasureSpec.makeMeasureSpec(w,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(h,View.MeasureSpec.EXACTLY));v.layout(0,0,w,h);val b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);v.draw(Canvas(b));val f=File("build/qa/$name.png");f.parentFile!!.mkdirs();f.outputStream().use{b.compress(Bitmap.CompressFormat.PNG,100,it)};b.recycle()}
}
